apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./base

commonLabels:
  canary: "true"
  deployment: opsani-canary
  name: opsani-canary-pod

patchesStrategicMerge:
  - canary.yaml

patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Deployment
      name: standard
    path: patch.json
