apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Deployment
      name: standard
    path: cleanup.json
